import React, { Component } from 'react';
// import { HashLink as Link } from 'react-router-hash-link';
// import { NavHashLink as Link } from 'react-router-hash-link';
import Link from 'next/link'
import Head from "next/head";

import Dropdown from '../dropdown/index.jsx';
import $ from 'jquery';

export default class Header extends Component {

  constructor(props) {
    super(props)
    this.state = {
    }
    this.HomePage = this.HomePage.bind(this);
    this.AboutusPage = this.AboutusPage.bind(this);
    this.ServicePage = this.ServicePage.bind(this);
    this.WordpressPage = this.WordpressPage.bind(this);
    this.ShopifyPage = this.ShopifyPage.bind(this);
    this.Blog = this.Blog.bind(this);
    this.CareersPage = this.CareersPage.bind(this);
    this.ContactusPage = this.ContactusPage.bind(this);
    this.filemakerPage = this.filemakerPage.bind(this);
    this.ErrorPage = this.ErrorPage.bind(this);
  }

  componentDidMount() {
    if (typeof window !== 'undefined') {


      this.menuToggle();
      // window.addEventListener("resize", this.menuToggle);


      $(window).scroll(function () {
        var scroll = $(window).scrollTop();

        if (scroll >= 74) {
          $('.header-container').addClass('sticky');
          $('.service-bg').addClass('fixed');
        } else {
          $('.header-container').removeClass('sticky');
          $('.service-bg').removeClass('fixed');
        }

      });
    }

  }

  componentWillUnmount() {
    if (typeof window !== 'undefined') {
      window.removeEventListener("resize", this.menuToggle);
    }
  }

  //menu toggle on mobile
  menuToggle() {
    if ($(".navbar-light .navbar-toggler").is(":visible")) {
      $(".navbar-light .navbar-nav .nav-item > i").click(function () {
        $(this).siblings('.submenu').slideToggle();
      });
    }
  }

  HomePage() {
    this.props.history.push('/');
  }
  AboutusPage() {
    this.props.history.push('/about-us');
  }

  ServicePage() {
    this.props.history.push('/services');
  }
  WordpressPage() {
    this.props.history.push('/wordpress');
  }
  ShopifyPage() {
    this.props.history.push('/shopify-experts');
  }

  Blog() {
    this.props.history.push('/blogs');
  }

  CareersPage() {
    this.props.history.push('careers');
  }
  ContactusPage() {
    this.props.history.push('/contact-us');
  }

  filemakerPage() {
    this.props.history.push('/filemaker');
  }
  ErrorPage() {
    this.props.history.push('/error');
  }

  render() {
    return (
      <header className="header-container">
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className="container" id="main-section">
          <nav className="navbar navbar-expand-lg navbar-light bg-light">
            <button
              className="navbar-toggler"
              type="button"
              data-toggle="collapse"
              data-target="#navbarTogglerDemo03"
              aria-controls="navbarTogglerDemo03"
              aria-expanded="false"
              aria-label="Toggle navigation"
            >
              <span className="navbar-toggler-icon"></span>
            </button>

            <div id="menu-container"></div>
            <Link href="/" className="navbar-brand">
              <img
                id="logo"
                className="logo"
                src="./hashtag-new-logo-header.svg"
                alt="logo"
              />
            </Link>

            <div className="mob-top-email d-block d-sm-none">
              <a href="mailto:info@hashtag-ca.com">
                <img src="/images/mob-top-email.svg" alt="email" />
              </a>
            </div>

            <div
              className="collapse navbar-collapse header-menu"
              id="navbarTogglerDemo03"
            >
              <ul className="navbar-nav mr-auto mt-2 mt-lg-0">
                <li className="nav-item">
                  <Link
                    href="/about-us"
                    className="nav-link"
                    activeclassName="active"
                  >
                    <a>
                      {" "}
                      About Us <span className="sr-only">(current)</span>
                    </a>
                  </Link>
                </li>

                <li className="nav-item">
                  <Link
                    href="/services"
                    className="nav-link"
                    activeclassName="active"
                  >
                    <a>
                      Services
                      <i className="fa fa-angle-down" aria-hidden="true"></i>
                    </a>
                  </Link>
                  <i className="fa fa-angle-down" aria-hidden="true"></i>
                  <ul className="submenu">
                    <div className="row m-0">
                      <div className="col-md-6 p-0">
                        <li>
                          <Link href="/services/wordpress-development">
                            Wordpress Development
                          </Link>
                        </li>
                        <li>
                          <Link href="/services/blockchain-development">
                            Blockchain Development
                          </Link>
                        </li>
                        <li>
                          <Link href="/services/design-and-prototyping">
                            Design and Prototyping
                          </Link>
                        </li>
                      </div>
                      <div className="col-md-6 p-0">
                        {/*<li><NavLink to="/services/aws">AWS</NavLink></li>*/}
                        <li>
                          <Link href="/services/filemaker">
                            FileMaker Pro Development
                          </Link>
                        </li>
                        <li>
                          <Link href="/services/ui-development">
                            UI Development
                          </Link>
                        </li>
                        <li>
                          <Link href="/services/database-and-backend">
                            DB & Backend Development
                          </Link>
                        </li>
                        {/*<li><NavLink to="/services/mobile-app">Mobile App Development</NavLink></li>*/}
                      </div>
                    </div>
                  </ul>
                </li>

                <li className="nav-item">
                  <Link
                    href="/shopify-experts"
                    className="nav-link"
                    activeclassName="active"
                  >
                    Shopify
                  </Link>
                </li>
                <li className="nav-item">
                  <Link
                    href="/blogs"
                    className="nav-link"
                    activeclassName="active"
                  >
                    Blog
                  </Link>
                </li>
                <li className="nav-item">
                  <Link
                    href="/careers"
                    className="nav-link"
                    activeclassName="active"
                  >
                    Careers
                  </Link>
                </li>
                <li className="nav-item">
                  <Link
                    href="/casestudies"
                    className="nav-link"
                    activeclassName="active"
                  >
                    Case studies
                  </Link>
                </li>
                <li className="nav-item">
                  <Link
                    href="/contact-us"
                    className="nav-link"
                    activeclassName="active"
                  >
                    Contact Us
                  </Link>
                </li>
              </ul>
              <div className="form-inline my-2 my-lg-0">
                <button className="btn-transparent btn-header-1 btn btn-outline-success my-2 my-sm-0">
                  <Link href="/" className="en-link">
                    En
                  </Link>
                </button>
                <Link href="/contact-us">
                  <button className="speak-btn btn-header-2 btn-white btn btn-outline-success my-2 my-sm-0">
                    <Link href="/contact-us">Let's Speak</Link>
                  </button>
                </Link>
              </div>
            </div>
          </nav>
        </div>
      </header>
    );
  }
}
